import Head from "next/head";
import PopularMovie from "@/movie/layouts/PopularMovie";
import UpComingMovie from "@/movie/layouts/UpComingMovie";
import Loading from "@/movie/components/Loading";
import useGetPopular from "@/movie/hooks/useGetPopular";

export default function Home() {
  const { loading } = useGetPopular();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sudo Films</title>
      </Head>
      <main>
        <div className="m-2">
          <UpComingMovie />
        </div>

        <hr className="w-full my-20" />
        {!loading ? (
          <div className="grid xl:grid-cols-4 lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1">
            <PopularMovie />
          </div>
        ) : (
          <Loading />
        )}
      </main>
    </>
  );
}
