import Head from 'next/head'
import PopularMovie from '@/movie/components/PopularMovie'
import UpComingMovie from '@/movie/components/UpComingMovie'
import Loading from '@/movie/components/Loading'
import useGetPopular from '@/movie/hooks/useGetPopular'

export default function Home() {
  const { loading } = useGetPopular()

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Sudo Films</title>
      </Head>
      <main className="bg-black">
        <div className="my-2">
          <UpComingMovie />
        </div>

        <hr className="w-full my-10" />
        {!loading ? <PopularMovie /> : <Loading />}
      </main>
    </>
  )
}
